### ISSUE TITLE
Presenter mode doesn't work right in Safari

### ISSUE THREAD

**Issue by davetron5000** [schacon/showoff#125] opened 2011-09-15 22:30 UTC
In Safari, presenter mode gets stuck in this cycle where the presenter view is auto-advancing slides, while the main view isn't doing anything.  It's possible to get to advance both, but then it always comes back to the auto-advance thing.  This (obviously) doesn't happen in chrome

**Comment by goncalossilva** [comment] 2012-03-06 02:45
I can't reproduce this on Safari 5.1.3. The presenter view was a bit changed lately, so I'm closing this for now.

If you hit this bug again, please reopen.

**Closed as completed by goncalossilva** 2012-03-06 02:45 UTC
