### ISSUE TITLE
custom showoff.css not working on heroku

### ISSUE THREAD

**Issue by blindsey** [schacon/showoff#124] opened 2011-09-14 17:28 UTC
How do I get a custom stylesheet to work on Heroku?

**Comment by goncalossilva** [comment] 2012-03-06 02:42
I can't reproduce this on master — heroku uses my CSS just fine.

I'm going to close this for now. If the bug is still present, please reopen.

**Closed as completed by goncalossilva** 2012-03-06 02:42 UTC

**Comment by blindsey** [comment] 2012-03-07 01:07
Yeah, I figured out a work around - move showoff.css up to the base directory.
