### ISSUE TITLE
Kramdown does not seem to work

### ISSUE THREAD

**Issue by cmoulliard** [schacon/showoff#188] opened 2012-06-21 17:27 UTC
Hi,

I have added as mardown engine --> "kramdown" like that

{ "name": "Charles Presentation",
  "description": "WebSocket Presentation",
  "author": "Charles Moulliard",
  "sections": [ 
     {"section":"one"},
     {"section":"two"} 
   ],
  "markdown" : "kramdown"
}

but the rendering of a kramdown table does not work. Do I have to configure something else ?

Regards,

Charles

**Comment by goncalossilva** [comment] 2012-06-24 04:53
It should be fixed on master. Try it out!

**Closed as completed** 2012-06-24 04:53 UTC

**Comment by cmoulliard** [comment] 2012-06-25 07:18
Can you explain how to deploy an new showoff server after doing a git pull ? I have done "rake gem" and "gem rake:install" but get "gem install mg"

Progresss-MacBook-Pro:chm chmoulli$ sudo rake gem:install
(in /Users/chmoulli/repositories/GitHub/showoff)
Please `gem install mg`
Progresss-MacBook-Pro:chm chmoulli$ sudo gem install mg
Successfully installed mg-0.0.8
1 gem installed
Installing ri documentation for mg-0.0.8...
Installing RDoc documentation for mg-0.0.8...
Progresss-MacBook-Pro:chm chmoulli$ sudo rake gem:install
(in /Users/chmoulli/repositories/GitHub/showoff)
Please `gem install mg`

**Comment by goncalossilva** [comment] 2012-06-25 08:18
You should use Bundler to manage showoff's gem dependencies: `bundle install`

**Comment by cmoulliard** [comment] 2012-06-25 09:20
Progresss-MacBook-Pro:chm chmoulli$ bundle install
Using rake (0.9.2.2) 
Using Ascii85 (1.0.1) 
Using ansi (1.4.2) 
Using blankslate (2.1.2.4) 
Using gli (1.6.0) 
Using json (1.7.3) 
Using mg (0.0.8) 
Using nokogiri (1.5.2) 
Using parslet (1.4.0) 
Using ruby-rc4 (0.1.5) 
Using pdf-reader (1.1.1) 
Using pdf-inspector (1.0.1) 
Using pdfkit (0.5.2) 
Using rack (1.4.1) 
Using rack-protection (1.2.0) 
Using rack-test (0.6.1) 
Using redcarpet (2.1.1) 
Using rmagick (2.13.1) 
Using tilt (1.3.3) 
Using sinatra (1.3.2) 
Using showoff (0.7.0) from source at . 
Using turn (0.9.5) 
Using bundler (1.1.4) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
sudo rake gem:install
Please `gem install mg`

**Comment by goncalossilva** [comment] 2012-06-25 09:23
`bundle exec rake gem:install` :)

**Comment by cmoulliard** [comment] 2012-06-25 09:40
There are still missing dependencies

sudo bundle exec rake gem:install

/Users/chmoulli/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find bundler (>= 0) amongst [bigdecimal-1.1.0, io-console-0.3, json-1.5.4, minitest-2.5.1, rake-0.9.2.2, rdoc-3.9.4](Gem::LoadError)

**Comment by goncalossilva** [comment] 2012-06-25 09:42
I can't reproduce this issue. Try not using sudo, or using `rvmsudo`.

**Comment by cmoulliard** [comment] 2012-06-25 09:50
Thx. That works now.

rvmsudo bundle exec rake gem:install
Password:
(in /Users/chmoulli/repositories/GitHub/showoff)
gem install dist/showoff-0.7.0.gem
Successfully installed showoff-0.7.0
1 gem installed
Installing ri documentation for showoff-0.7.0...
Installing RDoc documentation for showoff-0.7.0...

But table is not rendered when I make aagan a test with Kramdown !!!!

**Comment by goncalossilva** [comment] 2012-06-25 09:53
I know nothing about how Kramdown works... you still have `"markdown" : "kramdown"` on your configuration, correct? Is there some special configuration for Kramdown to render those tables?

**Comment by goncalossilva** [comment] 2012-06-25 09:55
Oh, and make sure you have Kramdown specified on your presentation's Gemfile and that you're running the presentation with `bundle exec`. Otherwise redcarpet will be used.

**Comment by cmoulliard** [comment] 2012-06-25 09:58
I still have "markdown" : "kramdown" in the json file of my project. There is no specific thing to do to use a table --> http://kramdown.rubyforge.org/quickref.html#tables

**Comment by cmoulliard** [comment] 2012-06-25 10:07
gem file contains "kramdown"

source :rubygems

gemspec

group :development do
  gem "mg"
  gem "turn"
  gem "rack-test"
  gem "pdf-inspector"
  gem "kramdown"
end

and project has been started like that 

bundle exec showoff serve

but redcarpet is still used.
